-- --------------------------------------------------------
-- CRIACAO TRIGGER AUDITA SALARIO
-- DROP TRIGGER TRG_AUDIT_SAL
-- TRIGGER PARA AUDITAR ALTERACOES DE SALARIO
-- --------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUDIT_SAL
   AFTER INSERT OR DELETE OR UPDATE OF SALARIO ON SALARIO
       FOR EACH ROW
     BEGIN
        IF INSERTING THEN
            INSERT INTO AUDITORIA_SALARIO 
                  VALUES (:NEW.COD_EMPRESA, :NEW.MATRICULA, 0, :NEW.SALARIO, USER, SYSDATE);

        ELSIF UPDATING THEN
            INSERT INTO AUDITORIA_SALARIO 
                  VALUES (:NEW.COD_EMPRESA, :NEW.MATRICULA, :OLD.SALARIO, :NEW.SALARIO, USER, SYSDATE);
        
        END IF;

     END;


-- TESTE
SELECT * FROM AUDITORIA_SALARIO;

SELECT * FROM SALARIO
 WHERE MATRICULA = 8;

UPDATE SALARIO SET SALARIO= SALARIO * 1.05 
 WHERE COD_EMPRESA = 1
   AND MATRICULA = 8;